### ISSUE TITLE
Issue Rendering structure from Minecolonies 1.20.1

### ISSUE THREAD

**Issue by flyingfoxjames** [ldtteam/Structurize#616] opened 2023-10-01 21:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.0.648-BETA

### MineColonies Version (if related bug)

1.1.195-BETA

### Related Mods and their Versions

forge version 47.1.0

### Current Behavior

After rendering certain blueprints (which I believe to be the fault of certain blocks but I don't know which ones or what to do about it) the game freezes and then crashes

### Expected Behavior

It should simply render the blueprint so I can move it around, rotate it, or look at it from different angles.

### Reproduction Steps

I have tested this on different worlds, so I am sure it has nothing to do with the environment. 
1. I simply open the Structurize menu with the build tool and use the "switch pack" and select the "Medieval Spruce" pack (although this happens with some other packs, this is just the one I have tested the most). 
2. Then I right click on a block with the tool, select the fundamentals tab and then the townhall build. 
3. Then I click on "townhall" and it renders the level 1 version. That works fine, along with the level 2 and 3 variants. 
4. However, once I select either level 4 or 5, the game is fine temporarily until I do anything else (such as leave the menu, try to move or rotate the blueprint, or any other action I can think of.) 
5. The game then freezes and then crashes shortly thereafter

### Logs

https://pastebin.com/T27UEYeb

### Anything else?

I tried fixing it by removing certain mods and messing around with it but nothing seemed to help

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment] 2023-10-23 16:04
Possible dupe of #619, fixed in f3a207f5d74b955a4abeba0976f3b558a3eac138

**Closed as completed by Nightenom** 2023-10-23 16:04 UTC
Labels: Bug
