### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by DraftySea1997** [ldtteam/Structurize#574] opened 2023-03-12 19:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.19

### Structurize Version

1.19.2-1.0.483-ALPHA

### MineColonies Version (if related bug)

1.19.2-1.0.1198-ALPHA

### Related Mods and their Versions

1. [1.19.x]-Epic-Knights-Armor-and-Weapons-6.6v
2. alexsmobs-1.20.1
3. AmbientSounds_FORGE_v5.2.1_mc1.19
4. appleskin-forge-mc1.19-2.4.2
5. architectury-6.2.43-forge
6. awesomedungeonend-forge-1.19.2-3.0.0
7. awesomedungeonnether-forge-1.19.2-3.0.0
8. awesomedungeonocean-forge-1.19.2-3.0.0
9. balm-4.5.3
10. betterfpsdist-1.19.1-1.6
11. BHMenu-Forge-1.19.2-1.3
12. BiomesOPlenty-1.19.2-17.1.1.150
13. blockui-1.19-0.0.64-ALPHA
14. Bookshelf-Forge-1.19.2-16.1.5
15. brutalbosses-1.19.1-5.5
16. Cataclysm-0.20-1.19.2-hotfix
17. caveore-1.19.2-2.3
18. citadel-1.12.11-1.19
19. cleancut-mc1.19-4.2-forge
20. clickadv-1.19.2-2.9
21. cloth-config-8.0.75-forge
22. comforts-forge-6.0.0+1.19.2
23. connectivity-1.19.1-3.3
24. cookingforblockheads-forge-1.19-13.2.1
25. CopperDrops-1.19-1.0
26. Copperized-1.19-2.5
27. corail_woodcutter-1.19.2-2.5.0
28. corpse-1.19.2-1.0.0
29. craftingtweaks-forge-1.19-15.1.0
30. CreativeCore_FORGE_v2.8.5_mc1.19.2
31. creeperoverhaul-2.0.4-forge
32. curios-forge-1.19.2-5.1.1.0
33. cursery-1.19.2-3.0
34. DeathCounter-1.19.2-1.2.1
35. deeperdarker-forge-1.1.3-forge
36. Delightful-1.19-3.1.1
37. domum_ornamentum-1.19-1.0.76-ALPHA-universal
38. dragonfight-1.19.2-2.4
39. DungeonsArise-1.19-2.1.51-beta
40. dusk-1.19.1-2.2
41. dynview-1.19.1-2.9
42. ecologics-forge-1.19.2-2.1.9
43. EnchantmentDescriptions-Forge-1.19.2-13.0.1
44. Enhanced-Farming-1.19-1.4.5
45. entityculling-forge-1.5.2-mc1.19.1
46. fallingthrough-1.19.2-2.6
47. FarmersDelight-1.19-1.2.0
48. farsight-1.19.1-2.0
49. ferritecore-5.0.2-forge
50. geckolib-forge-1.19-3.1.19
51. global_packs-forge-1.19.2-1.14.2_forge
52. goblintraders-1.7.3-1.19
53. HarderSpawners-1.19.2-40.2.23.0
54. hostilevillages-1.19.2-4.1
55. hourglass-1.19.1-1.2.1.1
56. infusedfoods-1.19.2-7.1.4
57. Jade-1.19.1-forge-8.1.1
58. jei-1.19.2-forge-11.3.0.262
59. journeymap-1.19.1-5.9.0beta2-forge
60. kleeslabs-forge-1.19-12.1.0
61. libraryferret-forge-1.19.2-3.0.0
62. limitedchunks-1.19.2-2.4
63. logprot-1.19.1-1.8
64. lootintegrations-1.19.1-1.6
65. memorysettings-1.19.2-2.2
66. minecolonies-1.19.2-1.0.1198-ALPHA
67. MouseTweaks-forge-mc1.19-2.23
68. multi-piston-1.19.2-1.2.19-ALPHA
69. mvs-3.1.3
70. naturalist-forge-2.1.1-1.19.2
71. Neat-1.19-32
72. notenoughcrashes-4.1.8+1.19.2-forge
73. Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.10
74. PlayerRevive_FORGE_v2.0.9_mc1.19.2
75. polymorph-forge-0.45.0+1.19.2
76. Rex's-AdditionalStructures-1.19-(v.4.0.1)
77. ScalingHealth-1.19.2-7.0.0+6
78. screenscale-1.19.2-2.3
79. shieldmechanics-1.19.2-3.5
80. silent-lib-1.19.2-7.0.2
81. smoothchunk-1.19.1-2.0
82. SoL-Carrot-1.19.2-1.14.0
83. sophisticatedbackpacks-1.19.2-3.18.24.703
84. sophisticatedcore-1.19.2-0.5.9.117
85. spoornarmorattributes-2.0.6-1.19-forge
86. spoornweaponattributes-4.0.9-1.19-forge
87. storageracks-1.19.2-1.1.4
88. structurize-1.19.2-1.0.483-ALPHA
89. TerraBlender-forge-1.19.2-2.0.1.125
90. The_Graveyard_1.12_(FORGE)_for_1.19.2
91. Towns-and-Towers-1.19-1.8.2
92. trashslot-forge-1.19-12.0.0
93. TreeChop-1.19.1-0.15.8
94. unstructured-0.5.2[FORGE]
95. vanillaplustools-1.19-1.1
96. wwoo_forge-3.1.7+1.19.2
97. zmedievalmusic-1.19.2-1.4

### Current Behavior

crashes when trying to place down watchtower for the nether keep 

### Expected Behavior

show a preview of the tower

### Reproduction Steps

1 click on change pack
2. click on crimson keep
3. click the first option
4. click guard tower
5. reopen world and click the ground

### Logs

https://gist.github.com/DraftySea1997/d1a215eff1b71323294035309358c59c

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by DraftySea1997** [comment] 2023-03-12 20:14
i also tried updating all the packs needed and it does the same thing

**Comment by Nightenom** [comment] 2023-10-23 16:06
Possible dupe of #619, fixed in 6d2bafac21f1a9b55305669880b19436b74efa2f

**Closed as completed by Nightenom** 2023-10-23 16:06 UTC
Labels: Bug
