### ISSUE TITLE
[Bridge fixed][Cannot load&place blueprints] IAngerable entities requires ServerWorld

### ISSUE THREAD

**Issue by SylviaFox** [ldtteam/Structurize#222] opened 2020-10-19 17:54 UTC
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.3
- MineColonies Version: 13.360 BETA
- Structurize Version:  13.92 ALPHA

## Expected behavior
the build tool GUI opening and letting me place the next building.

## Actual behavior
on clicking "Use Build Tool" the game freezes and then crashes.

## Steps to reproduce the issue

First, I placed down a Tavern Block
Then It suggested me like usually if I want to place it as a block or use the Build Tool
After that I chose the Build Tool option on which the game froze and crashed.

### Logs

- latest.log: https://gist.github.com/SylviaFox/ccb342067241f7bda1dbcf90145560ab
- crashlog:  https://gist.github.com/SylviaFox/52e464f722feb6544ca737066a9104b5

### Notes
I just played normally, this happend to me, on my Survival World where I had several buildings already ,with the Shepherd's Hut. I then proceeded to open a Creative world to see if it was just the one building. It worked fine at first, built my Builder's Hut, a Mine and sent my builder to now build a farm. Wanted to plan ahead but was stopped lol.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment] 2020-10-19 18:26
```
java.lang.ClassCastException: net.minecraft.client.world.ClientWorld cannot be cast to net.minecraft.world.server.ServerWorld
	at net.minecraft.entity.passive.WolfEntity.func_70037_a(WolfEntity.java:136) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1495) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeEntity.deserializeNBT(IForgeEntity.java:50) ~[?:?] {re:classloading}
```

did you create a custom scan?

**Comment by SylviaFox** [comment] 2020-10-19 18:29
> did you create a custom scan?

Nope, I don't even know what that is lol

**Comment by Nightenom** [comment] 2020-10-19 21:29
Oh no, another one

**Comment by Nightenom** [comment] 2020-10-19 21:41
@SylviaFox we need the name of the crashing schematic
@Raycoms if it's our schematic then rescan, also fix here:
After [BlueprintUtil.java#L527](https://github.com/ldtteam/Structurize/blob/version/1.16.3/src/main/java/com/ldtteam/structures/blueprints/v1/BlueprintUtil.java#L527) iterate all entities and remove anything that is net.minecraft.entity.IAngerable. Also please add note that IAngerable#readPersistentAngerSaveData(ServerWorld, CompoundNBT) needs ServerWorld

**Comment by SylviaFox** [comment] 2020-10-19 22:25
> @SylviaFox we need the name of the crashing schematic

I don't really know which one it is, every schematic I try from the minecolonies mod crashes it.

**Comment by Raycoms** [comment] 2020-10-20 07:01
This is so weird.

**Comment by Nightenom** [comment] 2020-10-21 14:24
Duplicate of #202, gonna be fixed soon

**Closed as completed by Nightenom** 2020-10-21 14:24 UTC
Labels: Duplicate, Next Major Version, Bug: Confirmed, 1.16, Compatibility: Vanilla
