### ISSUE TITLE
[BUG] Shape tool crashes world on GUI Screen (1.19.2)

### ISSUE THREAD

**Issue by TheRTGGaming** [ldtteam/Structurize#527] opened 2022-08-26 00:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.982

### Structurize Version

1.19.2-1.0.437

### Related Mods and their Versions

Forge: 1.19.2 - 43.1.2

### Current Behavior

The mod runs fine untill you use the shape tool

### Expected Behavior

Nothing but the game crashes.

### Reproduction Steps

use tool on ground and game crashes.

### Logs

https://gist.github.com/TheaRTGGaming/f7c65e64620eca4396e8deabb82d22af

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment] 2022-08-26 08:37
IWFM.  Did you do something other than just clicking it?

Although having said that, the settings menu shows up in the wrong place in the shape tool (it works ok in the build tool).  Which is odd, because they appear to be defined identically as far as I can see.
![image](https://user-images.githubusercontent.com/539951/186860363-2b4976b7-a798-4c17-bb0b-aff287bf696a.png)
(#528 fixes that part)

**Comment by TheRTGGaming** [comment] 2022-08-26 16:37
I will show you a screen shot of my GUI when i open the menu.

**Comment by TheRTGGaming** [comment] 2022-08-26 16:50
![2022-08-26_09 46 26](https://user-images.githubusercontent.com/48783483/186953501-5b7db5c5-aafd-4ec8-9de7-c11185588120.png)

when I clicked on the shape tool "Shape" menu and started typing it crashes the game. Idk if this is a bug or what but. in early versions that had a selective menu that have pre set shapes. so yea.

**Comment by uecasm** [comment] 2022-08-26 22:36
That's very strange.  My shape tool looks like this:
![image](https://user-images.githubusercontent.com/539951/186998564-1df8339a-f7a6-430b-9f4f-08ee3beb4369.png)

And there is no option that shows a "shape" text box.  The control does exist, but it's hidden automatically when the GUI is opened and there is no way to show it again.

Clearly something is crashing before it gets that far, but it must be something triggered by another mod that you have loaded.  You do have something that messes with the default font, for example; try removing that or other UI mods and see if it goes away.  Also, please reproduce the crash and paste your full log, not just the crash log.  There may be an earlier error that sheds more light on the eventual crash.

**Comment by TheRTGGaming** [comment] 2022-08-27 15:15
I figured it out. It only effects in survival mode. It works fine in a creative world but when used in a survival world it does not work correctly. Either my world got corrupted and can no longer use the shape tool due to a corruption. Or this might affect you on your end as well

**Comment by EnderKidRs** [comment] 2022-08-28 22:06
> I figured it out. It only effects in survival mode. It works fine in a creative world but when used in a survival world it does not work correctly. Either my world got corrupted and can no longer use the shape tool due to a corruption. Or this might affect you on your end as well

It does this for me too, except when I use the type bar to type in cube or any of the main buttons to pick the main block etc it will then crash. but only in survival for some reason.

**Comment by Talyda** [comment] 2022-08-28 22:46
I just tested this too - there is a text input box show up in survival, and I had it crash too (didn't test creative)  Structurize ending in .437

*edits* yeah, text box isn't there in creative

**Comment by uecasm** [comment] 2022-08-29 00:33
Ok, yeah.  Looks like the shape tool is just broken in 1.19 survival mode now.

With Structurize alone, it _used_ to not let you open the GUI at all (because it's a creative-only item).  The bit that prevents that was only partially removed so now it will just open incorrectly and will crash.  Meanwhile the part in MineColonies that allows you to use it in survival mode by assigning jobs to the builder was also removed without being properly replaced.

I started making a PR to fix it, but it was a bit more complex than I had first thought, so I'll have to get back to it later.  Unless Ray beats me to it. 😁

**Comment by TheRTGGaming** [comment] 2022-08-29 03:18
well if it is going to be fixed, then what will be a replacement tool if the shape tool is not going to be used for survival? I mean the shape tool is even craftable in survival.

**Comment by Raycoms** [comment] 2022-08-29 07:26
Survival usage of shape tool will be fixed

**Comment by uecasm** [comment] 2022-10-11 09:09
This should all be working now.

**Closed as completed by uecasm** 2022-10-11 09:09 UTC
Labels: Bug, 1.19
