### ISSUE TITLE
Unable to use any alpha for Structurize above 0.13.113-ALPHA with minecolonies 1.16.5

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/Structurize#282] opened 2021-02-04 00:14 UTC
![0kqcuFw 1](https://user-images.githubusercontent.com/10351221/106825892-68194900-664b-11eb-9234-93d911797753.png)

You don't need my life story so this image will suffice.

**Comment by ravenbuilder934** [comment] 2021-02-04 00:15
Duplicate of https://github.com/ldtteam/minecolonies/issues/6486 (this is actually on MineColonies's side)

**Closed as completed by ravenbuilder934** 2021-02-04 00:15 UTC
