### ISSUE TITLE
Town hall preview is rotated after mirroring

### ISSUE THREAD

**Issue by AndyClausen** [ldtteam/Structurize#633] opened 2023-11-22 22:36 UTC
I've placed down a Shire Town Hall, and noticed the preview of its boundaries are wrong when trying to place a building next to it. It's as if the building is rotated 180°. I placed it down mirrored and rotated 180°, so it might have something to do with mirroring.

![image](https://github.com/ldtteam/minecolonies/assets/16802212/e635ed00-9020-48ca-8b94-479e3bddf048)

In the screenshot, 1 is the preview of a new building (guard tower), 2 is the preview of the upgraded town hall, 3 is the current town hall. The preview of the town hall is flipped 180°, and the boundaries have followed (blue lines). As you can see, the "new" boundaries don't even include the actual building, so it's clearly wrong.

I've tried picking up the town hall and placing it down again in the correct orientation, but nothing changed.
mc 1.20.1
minecolonies 1.1.314-BETA
structurize 1.0.662-BETA

_Originally posted by @AndyClausen in https://github.com/ldtteam/minecolonies/issues/5006#issuecomment-1821087867_

**Comment by MotionlessTrain** [comment] 2023-11-23 07:53
Duplicate of #609

**Closed as completed** 2023-11-23 07:59 UTC
