### ISSUE TITLE
Freezing and eventually  crash to desktop

### ISSUE THREAD

**Issue by Howman** [ldtteam/Structurize#650] opened 2024-02-03 20:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.20

### Structurize Version

1.20.1-1.0.686-BETA

### Related Mods and their Versions

Minecraft 1.20.1
minecolonies: 1.20.1-1.1.461-BETA
structurize: 1.20.1-1.0.686-BETA
blockui: 1.20.1-1.0.139-BETA
domum_ornamentum: 1.20-1.0.154-BETA-universal
multipiston: 1.20-1.2.31-ALPHA
towntalk: 1.20.1-1.0.1
Forge: 47.2.20
JVM Arguments: -Xmx45G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

### Problem description

eventually  get Exit code: -805306369
Happens every time I goto select blue print  like medievalspruce then agriculture then husbandry then cowboy or altcowboy then the freeze for a long time then crash to desk top. But can go to my blue prints with out any problems and place and have builder build it  

### Anything else?

minecraft 1.20.1 when it asks what version there is no 1.20.1 just 1.20
Exit code: -805306369 seems to be memory related but i have 45 of my 64 gig of memory assigned to java but no problems with my own blue print have a 38 kb and can place it but not  a 2 kb cowboy.
nvidia rtx 3080
intel i9 11th gen

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment] 2024-02-03 20:18
hi, 45 Gb assigned to mc is not the best, usually less than 10 gb is enough (depending on size of modpack i recommend 4 to 8 gb)
also we need logs

**Comment by Howman** [comment] 2024-02-03 20:32
so i should lower memory then I got just over 200 mods not a mod pack
logs debug.log, latest.log,  all these and latest crash-reports 
https://1drv.ms/u/s!AsIR7CJxzJKoku97gBDJMaR4lywwcA?e=ngyYPb
https://1drv.ms/u/s!AsIR7CJxzJKoku97gBDJMaR4lywwcA?e=xQqkxS
https://1drv.ms/u/s!AsIR7CJxzJKoku98LqfVA-kUsH5B4Q?e=2asNTS
https://1drv.ms/t/s!AsIR7CJxzJKoku99PPWjev0aIMLngw?e=Sup04V

I think I sent a double of one of the logs

**Comment by Nightenom** [comment] 2024-02-04 18:06
The crash you sent might be caused by dynamictrees, otherwise i see nothing caused by us.

**Closed as completed by Nightenom** 2024-02-04 18:06 UTC

**Comment by Howman** [comment] 2024-02-05 03:23
I can not use Structurize except for my own blueprints it only crashes after waiting for 5 min + for it to bring up blueprint . dynamictrees was just added few days to a weeek ago and Structurize has been  doing this for a lot longer like 3 versions ago. Structurize would still not work before dynamictrees. I could try removing dynamictrees but do not think it would help. I do have a nother error that pops up every once in a while but not often it says something to do with "null" and i do not be-leave it has any thing to do with my problems. If error come up again I can post it .  I can also take a video record of problem when i try using Structurize

**Comment by Nightenom** [comment] 2024-02-05 10:29
I doubt its us, but you can try following: decrease ram to normal values (= below 10 gb) and get crash log - there you can see what is the cause, if it contains java.lang.OutOfMemoryError then you can try spark profiler below, else you need to report the crash to mod causing it

Spark: install spark (or check if its installed - command /spark) https://spark.lucko.me/download, and run `/spark heapsummary` and send here the link, along with it you can try normal spark profiler on both client and server thread (when your client starts lagging type commands `/sparkclient profiler start --only-ticks-over 60` and after few seconds `/sparkclient profiler stop`, then run the same command again but with `/spark` instead of `/sparkclient`). See for more info: https://spark.lucko.me/docs/guides/Finding-lag-spikes

**Comment by Howman** [comment] 2024-02-05 21:06
O.k lowered to 10 gb  then tryed again  it crashed but it did not make a report in crash-reports

https://spark.lucko.me/E0XnWp1A0C

here is that other error that comes up once and a while
The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.NonNullSupplier.get()" because "other" is null
Exit code: -1
so if i use spark before placing blueprint how would I get the info it collects cause when i go to set blue print it freezes and crash to desktop 

I guess i could start a new world and see what happens  also have Forgematica-0.1.3-mc1.20.1 could that be conflicting with Structurize in someway

**Comment by Nightenom** [comment] 2024-02-05 22:29
Nothing really suspicious in the memory dump, unless you get us any relevant logs then i only can suggest a binary search until you find the mod which causing the leak
