### ISSUE TITLE
barracks getting a trench

### ISSUE THREAD

**Issue by Swantsy** [ldtteam/Structurize#514] opened 2022-06-24 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **alpha** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.18

### Structurize Version

1.0.411-ALPHA

### MineColonies Version (if related bug)

1.0.792-ALPHA

### Related Mods and their Versions

FTB Presents Direwolf20 1.18 pack V. 1.4.1

### Current Behavior

![2022-06-24_17 20 59](https://user-images.githubusercontent.com/19387179/175568540-40c6f8c6-123f-4e2f-a414-a634cf798b9a.png)

upgrading the alternative medieval spruce alternative tier 3 to tier 4 this trench was made 

### Expected Behavior

not have the trench be dug.

### Reproduction Steps

upgrade the barracks from 3 to 4

### Logs

there was none

### Anything else?

I know it is not the latest version but this is a faulty build considering this is the only one with the error.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment] 2022-06-24 16:05
This rather belongs to https://github.com/ldtteam/minecolonies/issues/5006, as it is a schematic bug, not a bug in the mod itself.

**Comment by Raycoms** [comment] 2022-06-24 17:20
Yes, closed in favor of https://github.com/ldtteam/minecolonies/issues/5006

**Closed as completed by Raycoms** 2022-06-24 17:20 UTC
Labels: Bug
