### ISSUE TITLE
[1.15.2] Startup error with Optifine & OptiForge

### ISSUE THREAD

**Issue by RobinVanCauter** [ldtteam/Structurize#112] opened 2020-03-31 19:58 UTC
### Structurize version

Version: `version/1.15` branch (I built from source to make sure it wasn't fixed in a recent source code change)

### Problem

Line [91](https://github.com/ldtteam/Structurize/blob/0acea487b9a65cd1fa75dc95887978c70ab1fd65/src/main/java/com/ldtteam/structurize/optifine/OptifineCompat.java#L91) and [95](https://github.com/ldtteam/Structurize/blob/0acea487b9a65cd1fa75dc95887978c70ab1fd65/src/main/java/com/ldtteam/structurize/optifine/OptifineCompat.java#L95) comment out variables with `//todo` inside the [optifine compatibility layer](https://github.com/ldtteam/Structurize/blob/version/1.15/src/main/java/com/ldtteam/structurize/optifine/OptifineCompat.java).
The line below each of those 2 lines, reference those commented out variables, thus, when the compatibility layer gets loaded; it crashes and fails to load during forge bootup.

When I commented out the 2 lines referencing the commented out variables, the game loads up correctly and OptiFine actually works with shaders and everything :)

### Steps to reproduce the problem

1. Add the latest [OptiForge](https://github.com/ZekerZhayard/OptiForge) version
2. Add the latest [Optifine](https://optifine.net/downloads) preview
3. Boot the game
4. Fails to boot

**Comment by Nightenom** [comment] 2020-03-31 20:01
Ok, will trust your research and push that in.

**Comment by Raycoms** [comment] 2020-03-31 20:02
@T-Grave with those two disabled do the schematic display correctly?

**Comment by RobinVanCauter** [comment] 2020-03-31 20:08
@Nightenom @Raycoms 

I do have to admit, I did not actually test all mods extensively, I was just happy I was able to load up a world in the Valhesia 2 modpack after patching this, with shaders.

I expect there could still be rendering issues (seeing as there was a //todo and we're essentially turning off parts of the compat layer). But I'd argue it's still an improvement over not being able to launch at all.

Can you explain me what I should test exactly @Raycoms then I will do so right now? (I'm sorry, I have not yet played the Structurize mod myself in this modpack, only started playing with it recently)

**Comment by Nightenom** [comment] 2020-03-31 20:12
Actually I'm not aware of using those methods rn (in the rendering pipeline), so basically it should not work as intended or optifine itself hasn't ported this part yet
Mostly we need that for preview thing which you can access using buildtool (gold scepter)
edit: yeah, no signs of using it anywhere <https://github.com/ldtteam/Structurize/search?q=OptifineCompat&type=Code>

**Comment by Raycoms** [comment] 2020-03-31 20:14
@T-Grave basically right click the buildtool to test if the previews render correctly.

**Comment by Raycoms** [comment] 2020-03-31 20:16
@Nightenom I pushed a fix for it right now.

**Comment by Nightenom** [comment] 2020-03-31 20:17
Does it actually do anything? Since it's not used we don't need to call it
If it works out of the box (which it may) then it's ok, but I doubt

**Comment by Raycoms** [comment] 2020-03-31 20:18
I'm not sure it is doing anything at all atm. It would have to be tested.

**Comment by RobinVanCauter** [comment] 2020-03-31 20:18
I will let you guys know in a few minutes :)

Edit: I'm sorry guys, taking a bit longer, was doing a fresh install of the modpack, enabling shaders takes a while the first time :1st_place_medal:

**Comment by RobinVanCauter** [comment] 2020-03-31 20:39
![image](https://user-images.githubusercontent.com/7956579/78072929-35a21e00-73a0-11ea-8f8e-f99e3b07d386.png)

I expect it's supposed to preview something here?

This is without the latest patch you pushed @Raycoms

**Comment by Raycoms** [comment] 2020-03-31 20:40
yeah its supposed to render the fortress cornerkennel somewhere around there

**Comment by Raycoms** [comment] 2020-03-31 20:40
Move it around with the arrows up and down a bit to see if it appears somewhere

**Comment by RobinVanCauter** [comment] 2020-03-31 20:44
Don't think anythings happening. Also pressing the green mark never does anything and throws a "Cannot build" error in the console. Pressing the "copy/paste" buttons does actually make a huge structure appear.

Should I try with your latest patch?

**Comment by Nightenom** [comment] 2020-03-31 20:46
If there wasn't a preview in the place of the structure (before you placed it) then it's not working
You don't need to, it won't change anything

**Comment by Raycoms** [comment] 2020-03-31 20:58
So I guess we don't support optifine in 1.15 yet =P

**Comment by Raycoms** [comment] 2020-03-31 20:58
We're rendering those things on the vanilla layers now though, so that's weird.

**Comment by RobinVanCauter** [comment] 2020-03-31 21:05
I did one last test for you guys: using OptiFine but without any shaders enabled. Lots of folks love to use optifine for the FPS boost it gives, not necessarily for the shaders.

But it looks like the previews aren't working in that case either.

**Comment by Raycoms** [comment] 2020-03-31 21:12
Can you try the version that I just pushed? (Will be on curse within minutes)

**Comment by RobinVanCauter** [comment] 2020-03-31 21:16
Will do

**Comment by RobinVanCauter** [comment] 2020-03-31 21:31
Tested with 0.293-ALPHA: The game boots up fine with OptiFine enabled, shaders work, preview doesn't.

**Comment by Raycoms** [comment] 2020-03-31 22:14
Even without shaders the preview doesn't load?

**Comment by Nightenom** [comment] 2020-04-01 11:24
@T-Grave which optifine version are you using? I can't get preview_OptiFine_1.15.2_HD_U_G1_pre12 working (crash when loading). If it's a different version please upload it somewhere and send to me.

Also which and where you got your shaders so I can test them

**Comment by Nightenom** [comment] 2020-04-01 13:01
Can you try this if it works?
<https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Structurize_Branches_Build/36551:id/build/libs/structurize-0.10.211-PERSONAL.jar>

**Comment by RobinVanCauter** [comment] 2020-04-01 22:36
@Nightenom I was using pre10, are you using OptiForge and MixinLoader as well? You need those to make optifine work on forge atm (no official forge support yet)

Going to sleep now, but I will try tomorrow and let you know.

**Comment by Nightenom** [comment] 2020-04-02 07:18
Nope, it gets even worse with the mods you suggested, however, you should be able to run it outside dev space

**Comment by Nightenom** [comment] 2020-04-08 15:43
@T-Grave can you please test the version above?

**Comment by RobinVanCauter** [comment] 2020-04-15 10:15
@Nightenom I'm sorry for the delay, got very busy for work.

Just tested, same result as before; previews not working.

In terms of getting Optifine to work locally for yourself: another important variable was the Forge version, it has to be  >=31.1.32

**Comment by Nightenom** [comment] 2020-04-16 12:49
@T-Grave @NiickNICHEN @theoklm new version to try, if this one won't work I'm gonna make another try when optifine team manages to publish forge compatible version
<https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Structurize_PullRequests2_BuildAndTest/37124:id/build/libs/structurize-0.10.151-PR.jar>

**Comment by RobinVanCauter** [comment] 2020-04-16 15:54
@Nightenom no improvement :(

Totally understand you wanting to wait , will be a lot easier to fix once you can test it properly yourself :)

Thanks for trying tho!

**Comment by TaylorMaker54** [comment] 2020-04-20 19:00
Nightenom, I tried your structurize-0.10.151-PR with MixinBootstrap-1.0.2.jar, OptiForge-MC1.15.2-0.1.11, preview_OptiFine_1.15.2_HD_U_G1_pre13, It displayed the preview in game fine while in creative, but would not even give me a menu when trying in survival, I used both SEUS-Renewed-v1.0.1 and Sildurs Vibrant Shaders v1.27 Extreme-VL shaders I just figured i would post my findings, thanks for all the great work you guys put into this mod.

**Comment by Nightenom** [comment] 2020-04-20 19:23
thanks for the info, that's really weird it works in creative while not in survival, BUT at least it works :)

**Comment by TaylorMaker54** [comment] 2020-04-20 21:27
@Nightenom I realized i did not have the most recent version of Structurize my first time trying.
This setup works for me, I hope the OP can use it.

forge-31.1.47

OptiForge-MC1.15.2-0.1.11
MixinBootstrap-1.0.2
preview_OptiFine_1.15.2_HD_U_G1_pre13
structurize-0.10.302-ALPHA
minecolonies-0.11.840-BETA-universal
jei-1.15.2-6.0.0.3

Shaders i tested
SEUS-Renewed-v1.0.1
Sildurs Vibrant Shaders v1.27 Extreme-VL

**Comment by Nightenom** [comment] 2020-04-20 21:38
@TaylorMaker54 so it works with the current latest version?
or with the one I posted recently (structurize-0.10.151-PR.jar)?

**Comment by TaylorMaker54** [comment] 2020-04-20 21:56
@Nightenom Yes. The current at the moment i believe is structurize-0.10.302-ALPHA and it does work

**Closed as completed** 2020-05-03 14:22 UTC
